name: Docker Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t sistema-editais:latest .